Description: Project 2, Create Bucket

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    BucketName: !Sub ${EnvironmentName}-Bucket
    Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName} Bucket for Project